# Generated by Django 5.2.3 on 2025-12-18 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_feedback_created_at_alter_appointment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointmentProvider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointmentService', to='booking.servicetype'),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AppointmentFeedback', to='booking.appointment'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
    ]
