# Generated by Django 5.2.3 on 2025-12-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointmentslot_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointmentFeedback', to='booking.appointment'),
        ),
    ]
